export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_USERPROFILE = "GET_USERPROFILE";
export const EDIT_USERNAME = "EDIT_USERNAME";
export const EDIT_FIRSTNAME = "EDIT_FIRSTNAME";
export const EDIT_LASTNAME = "EDIT_LASTNAME";
